AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SubscriberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriberTable
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref SubscriberTable
      Events:
        Subscribe:
          Type: Api
          Properties:
            Path: /subscribe
            Method: post
        Unsubscribe:
          Type: Api
          Properties:
            Path: /unsubscribe
            Method: get
        SendEmail:
          Type: Schedule
          Properties:
            Schedule: rate(1 week)

  SubscriberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SubscriberTable
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
